#!/bin/bash

wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz && tar xzfv GeoLite2-City.tar.gz --wildcards '*/GeoLite2-City.mmdb' --strip-components 1; rm -fv GeoLite2-City.tar.gz
{ 
  wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country-CSV.zip && unzip -oj GeoLite2-Country-CSV.zip '*/GeoLite2-Country-Blocks-IPv4.csv';
}; rm -fv GeoLite2-Country-CSV.zip
