#!/bin/bash

wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz && gunzip -f GeoLite2-City.mmdb.gz
{ wget http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip && unzip -o GeoIPCountryCSV.zip; }; rm -f GeoIPCountryCSV.zip
