--[[

  Generate (or set) a unique tag for filenames generated by a server instance.

]]--

return setmetatable({}, { __index = function(_, name)
  if name == "tag" then return cs.serverport end
end })
