/*
 * Generated by dtrace(1M).
 */

#ifndef	_SBTRACE_H
#define	_SBTRACE_H

#ifndef WIN32
#include <unistd.h>
#endif

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	SAUERBRATEN_ALIAS_ENTRY(arg0, arg1, arg2, arg3) \
	__dtrace_sauerbraten___alias__entry(arg0, arg1, arg2, arg3)
#define	SAUERBRATEN_ALIAS_ENTRY_ENABLED() \
	__dtraceenabled_sauerbraten___alias__entry()
#define	SAUERBRATEN_ALIAS_RETURN(arg0) \
	__dtrace_sauerbraten___alias__return(arg0)
#define	SAUERBRATEN_ALIAS_RETURN_ENABLED() \
	__dtraceenabled_sauerbraten___alias__return()
#define	SAUERBRATEN_COMMAND_ENTRY(arg0, arg1, arg2, arg3) \
	__dtrace_sauerbraten___command__entry(arg0, arg1, arg2, arg3)
#define	SAUERBRATEN_COMMAND_ENTRY_ENABLED() \
	__dtraceenabled_sauerbraten___command__entry()
#define	SAUERBRATEN_COMMAND_RETURN(arg0) \
	__dtrace_sauerbraten___command__return(arg0)
#define	SAUERBRATEN_COMMAND_RETURN_ENABLED() \
	__dtraceenabled_sauerbraten___command__return()
#define	SAUERBRATEN_VAR_ENTRY(arg0, arg1) \
	__dtrace_sauerbraten___var__entry(arg0, arg1)
#define	SAUERBRATEN_VAR_ENTRY_ENABLED() \
	__dtraceenabled_sauerbraten___var__entry()
#define	SAUERBRATEN_VAR_RETURN(arg0, arg1) \
	__dtrace_sauerbraten___var__return(arg0, arg1)
#define	SAUERBRATEN_VAR_RETURN_ENABLED() \
	__dtraceenabled_sauerbraten___var__return()


extern void __dtrace_sauerbraten___alias__entry(char *, char *, char *, char *);
extern int __dtraceenabled_sauerbraten___alias__entry(void);
extern void __dtrace_sauerbraten___alias__return(char *);
extern int __dtraceenabled_sauerbraten___alias__return(void);
extern void __dtrace_sauerbraten___command__entry(char *, char *, char *, char *);
extern int __dtraceenabled_sauerbraten___command__entry(void);
extern void __dtrace_sauerbraten___command__return(char *);
extern int __dtraceenabled_sauerbraten___command__return(void);
extern void __dtrace_sauerbraten___var__entry(char *, char *);
extern int __dtraceenabled_sauerbraten___var__entry(void);
extern void __dtrace_sauerbraten___var__return(char *, int);
extern int __dtraceenabled_sauerbraten___var__return(void);

#else

#define	SAUERBRATEN_ALIAS_ENTRY(arg0, arg1, arg2, arg3)
#define	SAUERBRATEN_ALIAS_ENTRY_ENABLED() (0)
#define	SAUERBRATEN_ALIAS_RETURN(arg0)
#define	SAUERBRATEN_ALIAS_RETURN_ENABLED() (0)
#define	SAUERBRATEN_COMMAND_ENTRY(arg0, arg1, arg2, arg3)
#define	SAUERBRATEN_COMMAND_ENTRY_ENABLED() (0)
#define	SAUERBRATEN_COMMAND_RETURN(arg0)
#define	SAUERBRATEN_COMMAND_RETURN_ENABLED() (0)
#define	SAUERBRATEN_VAR_ENTRY(arg0, arg1)
#define	SAUERBRATEN_VAR_ENTRY_ENABLED() (0)
#define	SAUERBRATEN_VAR_RETURN(arg0, arg1)
#define	SAUERBRATEN_VAR_RETURN_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _SBTRACE_H */
